### ISSUE TITLE
Persistence of HNSW

### ISSUE THREAD

**Issue by gasabr** [rust-cv/hnsw#14]
Thanks for the lib!

Do you have any plans or ideas on implementing save and load functionality in this library?

**Comment by vadixidav** [comment]
It currently supports that with serde serialization. You can disable it, but it's actually on by default.

**Comment by vadixidav** [comment]
Actually, I am going to reopen this because most of the included Hamming and Euclidean impls don't have serde support, even though HNSW does.

**Comment by gasabr** [comment]
Sorry, I'm kinda new to rust, is there a way for me to save `HNSW<Euclidian<f32x4>>`? From your question in `packed_simd` repo I understood that it would be enough to derive serialize for `Simd` types and Euclidean will become serializable too, lacking that what can I do? Probably contribution with a lot of wrapper types?

**Comment by vadixidav** [comment]
@gasabr Currently, you can create a wrapper type that implements serialize. I can add those impls to the library when I get a chance. If you need a solution right now, I recommend copying the euclidean distance impls from the library and use it with a wrapper. it really isn't ideal, so I will add wrappers myself instead of waiting for serialize to get impled upstream in packed_simd.

**Comment by gasabr** [comment]
Thank you very much! Will try it out

**Comment by gasabr** [comment]
If you need any help on that -- ping me, I'm very interested in getting saving/loading functionality and can do some basic staff in Rust;)

**Comment by vadixidav** [comment]
@gasabr So, I did take a look at the current state of affairs, and it seems that `packed_simd` is planning to be rewritten to use const generics. That would also make the impls much cleaner for us with `serde`. My current disposition is to probably wait a while before we actually add this. Alternatively, we can create impls for serialize and deserialize on a wrapper for every single array length of `Hamming` and `Euclidean`. Personally, I would rather not do that work because this is all going to change soon anyways. My current disposition is that if you would like to add these impls, feel free to do so and I will merge it. Make sure it is gated behind the `serde-impl` feature. Ultimately, we should probably release a new version of `hnsw` once packed simd supports const generics and we will go from there.

In the meantime, I will add impls for `Euclidean<Vec<f32>>` and `Hamming<Vec<u8>>`. This will let you easily load and store the HNSW at the cost of speed. For floats this will probably have little speed degradation, but for bytes this will severely impact the performance of distance computation (I checked on [Godbolt](https://godbolt.org/) and it isnt optimizing it). It turns out that this kind of thing is pretty fast anyways since HNSW doesn't have to check distance quite too much, but it will impact your performance, especially if you have enormous bitstrings (>1K).

**Comment by vadixidav** [comment]
Just noticed that I already added impls for `Euclidean<Vec<f32>>` and `Hamming<Vec<u8>>` not too long ago, so that should be good for now.

**Comment by vadixidav** [comment]
@gasabr This is now solved. I switched everything to pure macros and put in the effort to get every numeric combination working with `Serialize` and `Deserialize`. It now also has `From` and `Into` impls for arrays and `From` for slices. This functionality is now out in release `0.4.0`. It now uses u8xN types instead of u128xN types for SIMD, which simplifies interaction with bytes.
